<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    
    <Version>2.1.0</Version>
    <AssemblyVersion>2.1.0</AssemblyVersion>
    <FileVersion>2.1.0</FileVersion>
    <Company>JP Consulting</Company>
    <Product>LB Missing Games Checker Plugin</Product>
    <Description>Check which games you have and don't have for a selected platform in LaunchBox.</Description>
    <Copyright>Copyright © 2026</Copyright>
    <ApplicationIcon>mgc.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="mgc.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Unbroken.LaunchBox.Plugins">
      <HintPath>H:\LaunchBoxDev\Core\Unbroken.LaunchBox.Plugins.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>